[Lattice]
symmetry = "Rectangular"
lengths = [ 12500.0, 12500.0,]
background_index = 1.0
coupling = "SPP"
finite_extent = [ 10, 10,]

[Grid]
minimum_wavevector_im = -628318.5307179586
maximum_wavevector_im = 628318.5307179586
minimum_wavenumber_icm = 840
maximum_wavenumber_icm = 885
number_of_wavevectors = 199
number_of_wavelengths = 200

[Particle]
radius_nm = 1000.0
internal_dielectric_function_file = "SiC.tab"

[Field]
polarisation = "TM"
probe = "EnsembleAverage"
